### ISSUE TITLE
Compile to 2.12

### ISSUE THREAD

**Issue by ticofab** [ticofab/aws-request-signer#13]

**Comment by abankowski** [comment]
👍 I'd love to see version for Scala 2.12 published. Already working on it locally, simply adding `2.12.2` to `crossScalaVersions` seems to be fine.

**Comment by alex1712** [comment]
You have as a PR https://github.com/ticofab/aws-request-signer/pull/14

**Comment by ticofab** [comment]
fixed in 0.5.0
