### ISSUE TITLE
Getting wrong signature  with current version

### ISSUE THREAD

**Issue by alex1712** [ticofab/aws-request-signer#15]
After the update to last version I am getting a wrong signature, I was debugging the issue and found out that the problem happen with the current code in the headerAsString function

```
    def headerAsString(header: (String, Object), method: String): String = {
      if (header._1.equalsIgnoreCase(CONNECTION)) {
        CONNECTION + CLOSE
      } else if (header._1.equalsIgnoreCase(CONTENT_LENGTH) && header._2.equals(ZERO) && method.equalsIgnoreCase("DELETE")) {
        header._1.toLowerCase + ':'
      } else {
        header._1.toLowerCase + ':' + header._2
      }
    }
```

If I change this function to the old version not checking the DELETE method, then the signature is accepted by AWS, any idea why is that happening? Here the code which works for me:
```
    def headerAsString(header: (String, Object), method: String): String = {
      if (header._1.equalsIgnoreCase(CONNECTION)) {
        CONNECTION + CLOSE
      } else if (header._1.equalsIgnoreCase(CONTENT_LENGTH) && header._2.equals(ZERO)) {
        header._1.toLowerCase + ':'
      } else {
        header._1.toLowerCase + ':' + header._2
      }
    }
```

**Comment by alex1712** [comment]
I am thinking about it and shouldn't this condition be an OR? Like
```
else if ((header._1.equalsIgnoreCase(CONTENT_LENGTH) && header._2.equals(ZERO)) || method.equalsIgnoreCase("DELETE")) {
```

**Comment by ticofab** [comment]
Hey Alex, thanks for opening this! I tracked the issue back to the Java version of this library. The fix seems to be this one: https://github.com/inreachventures/aws-signing-request-interceptor/pull/12

As you're already on the topic, would you be able to try it on your local copy and port it if successful? Thanks a bunch!

**Comment by alex1712** [comment]
Hi, thanks for answering. I will try to check it this week, but I am not sure if I will have the time.

**Comment by abankowski** [comment]
@alex1712 I decided to help you as this issue is currently a blocker for me. 

@ticofab I'd appreciate if you review, merge and publish a fixed version. I will work on a local snapshot for a while.

**Comment by alex1712** [comment]
Thanks you very much @abankowski

**Comment by ticofab** [comment]
@abankowski @alex1712 version 0.5.1 is up - thanks guys!
