### ISSUE TITLE
Encoding algorithm used differs from what Amazon expects

### ISSUE THREAD

**Issue by steven-collins-omega** [ticofab/aws-request-signer#17]
The Amazon documentation for constructing the canonical query string states:

> URI-encode each parameter name and value according to the following rules:
> 
> Do not URI-encode any of the unreserved characters that RFC 3986 defines: A-Z, a-z, 0-9, hyphen ( - ), underscore ( _ ), period ( . ), and tilde ( ~ ).
> Percent-encode all other characters with %XY, where X and Y are hexadecimal characters (0-9 and uppercase A-F). For example, the space character must be encoded as %20 (not using '+', as some encoding schemes do) and extended UTF-8 characters must be in the form %XY%ZA%BC.

This differs in two important respects from the scheme java.net.URLEncoder uses - it specifies a slightly different set of non-alphanumeric special characters not to encode, and it _does_ use + for space.

What is also true, in my experience, about what Amazon expects -- which is currently incorrectly documented by them -- is that the canonical _URI_ must also be encoded using the same rules quoted above. This means that `*` and `,` characters, which are not uncommon in Elasticsearch URIs, must be percent-encoded.

**Comment by ticofab** [comment]
Hey @steven-collins-omega -- thanks for opening this and sorry for the century-long time it took me to respond. Do you know of any encoding library that uses the specified set, or maybe have time to provide an improvement? As far as I know, the way currently used in this project works, or at least I haven't received any complaints about that, so maybe Amazon can be a little flexible sometimes ;)

**Comment by ticofab** [comment]
Closing because this project is deprecated (see README) and because of no further reaction in a long time.
