### ISSUE TITLE
Jar is not available for scala 2.13

### ISSUE THREAD

**Issue by pratikadhau11** [ticofab/aws-request-signer#24]
We are migrating to scala 2.13 from 2.12 in current project. We are using this library for aws request signing. Unfortunately on maven jar for scala 2.13 is not available for version 0.5.2. (https://mvnrepository.com/artifact/io.ticofab/aws-request-signer_2.12/0.5.2), though I see built.sbt has scala version 2.13. I guess this need to be published on maven.

**Comment by ticofab** [comment]
Hi @pratikadhau11 , thanks for your message. I'm happy to hear that this library has helped. Unfortunately this project is no longer maintained . There are alternatives, see the README. Good luck!
