### ISSUE TITLE
Can you give me an example of writing data into es?

### ISSUE THREAD

**Issue by SeeWei1985** [ticofab/aws-request-signer#4]
Thank you.

**Comment by ticofab** [comment]
I'm afraid that examples about using ElassticSearch are beyond the scope of this project :) It depends on the ES client that you are using. Check this out: https://github.com/scalastuff/esclient

**Comment by hekaldama** [comment]
@ticofab if you have one that satisfies your quote in the README.md, that would suffice to get us started. Looking at the test suite is helpful, but I am failing to connect the last dots on getting it _actually_ working with AWS ES.
