### ISSUE TITLE
Query string order

### ISSUE THREAD

**Issue by joprice** [ticofab/aws-request-signer#9]
According to this doc, query params need to be ordered in the canonical request. http://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html

**Comment by ticofab** [comment]
So the query params should first be sorted in alphabetical order, is that right?

**Comment by joprice** [comment]
From that doc:

"Sort the parameter names by character code point in ascending order. For example, a parameter name that begins with the uppercase letter F precedes a parameter name that begins with a lowercase letter b."

**Comment by ticofab** [comment]
Cool, thanks for opening. Marking as "enhancement" as It seems to work anyway.

**Comment by joprice** [comment]
I couldn't get it to work for elasticsearch-service when two query params were provided.

**Comment by ticofab** [comment]
Ouch!

**Comment by ticofab** [comment]
hey @joprice , finally I had time to fix this. Please try it on version 0.4.1 and reopen this bug if the issue still persists.
